name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --include=dev
      env:
        npm_config_build_from_source: false

    - name: Lint code
      run: npm run lint

    - name: Create reports directory
      run: mkdir -p reports/junit

    - name: Run unit tests
      run: npm test
      env:
        CI: true
        JEST_JUNIT_OUTPUT_DIR: reports/junit

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: reports/
        retention-days: 5

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: coverage/
        retention-days: 5