name: Test and Validate

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        env:
          npm_config_build_from_source: false

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test
        env:
          CI: true

      - name: Run end-to-end tests
        run: npm run test:e2e
        continue-on-error: true

  # Test summary
  test-summary:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Test Summary
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Windows  | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| macOS    | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Testing Only" >> $GITHUB_STEP_SUMMARY
          echo "- This workflow only runs tests and validation for PRs" >> $GITHUB_STEP_SUMMARY
          echo "- Builds are created only when code is merged to main branch" >> $GITHUB_STEP_SUMMARY
          echo "- This saves resources and provides faster PR feedback" >> $GITHUB_STEP_SUMMARY
